export const ON_CHANGE = 'ON_CHANGE'
export const FETCH_IMAGES_BEGIN = 'FETCH_IMAGES_BEGIN'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'
